spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boris_db
    username: postgres
    password: postgres
eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
